app:
  image:
    repository: aeternity/aerepl_http
    tag: "latest"
  service:
    port: 4000
  ingress:
    enabled: true
    hosts:
      - host: "repl.dev.superk8s.de"
        paths:
          - path: "/"



