app:
  nameOverride: "superhero"
  imagePullSecrets:
    - name: "dockerhub-secret"
  image:
    repository: "superherodotcom/sup6cga"
    tag: "develop"
    pullPolicy: "Always"
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"
  ingress:
    enabled: "true"
    hosts:
      - host: "superhero.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-614-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-614"
      - host: "pr-618-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-618"
      - host: "pr-623-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-623"
      - host: "pr-625-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-625"
      - host: "pr-630-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-630"
      - host: "pr-632-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-632"
      - host: "pr-641-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-641"
      - host: "pr-663-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-663"
      - host: "pr-673-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-673"
      - host: "pr-675-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-675"
      - host: "pr-676-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-676"
      - host: "pr-678-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-678"
      - host: "develop-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "develop"
      - host: "pr-659-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-659"
  versions:
    - version: "pr-614"
      gitSha: "3d4359a427c8e19426db8c56b3b1326627099264"
    - version: "pr-618"
      gitSha: "d59d26a6761e66a0b0e3a0d1b364411d62f34c1d"
    - version: "pr-623"
      gitSha: "aceb201047db3f3d77c52eadaa29abc68456e72d"
    - version: "pr-625"
      gitSha: "ff92ac63a569ef041fb9c2637eec19dc3e8c9aff"
    - version: "pr-630"
      gitSha: "07b8ef6e1651921f9c45cab941a8886e86ca1e72"
    - version: "pr-632"
      gitSha: "5973793ca3406a63dbe6a05e5724ad6bec9d2716"
    - version: "pr-641"
      gitSha: "415c79d4ac6fb9e4bb964329a8db2ed793e0d2dc"
    - version: "pr-663"
      gitSha: "5dbc28c7107cba133603cbb7de68dded8444bca2"
    - version: "pr-673"
      gitSha: "404a14956b8863995ba4e9315c604213fd69edab"
    - version: "pr-675"
      gitSha: "56aaca260be85969908e41dfff8489080949b3b3"
    - version: "pr-676"
      gitSha: "9584377e12bafafc41335c549720440c6375b1a1"
    - version: "pr-678"
      gitSha: "7e6535c436c575a10ef052aad50475a1002eba2a"
    - version: "develop"
      gitSha: "020fa00d5013f349b40eb30cce0cea62c29bd66b"
    - version: "pr-659"
      gitSha: "90851401a0dbdc1b64a222fe3dc9e18ffe1fb1ab"
