app:
  nameOverride: "superhero"
  imagePullSecrets:
    - name: "dockerhub-secret"
  image:
    repository: "superherodotcom/sup6cga"
    tag: "develop"
    pullPolicy: "Always"
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "128Mi"
  ingress:
    enabled: "true"
    hosts:
      - host: "superhero.stg.service.aepps.com"
        paths:
          - path: "/"
      - host: "pr-614-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-614"
      - host: "pr-618-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-618"
      - host: "pr-619-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-619"
      - host: "pr-623-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-623"
      - host: "pr-625-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-625"
      - host: "develop-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "develop"
      - host: "pr-626-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-626"
      - host: "pr-627-superhero.stg.service.aepps.com"
        paths:
          - path: "/"
            version: "pr-627"
  versions:
    - version: "pr-614"
      gitSha: "3d4359a427c8e19426db8c56b3b1326627099264"
    - version: "pr-618"
      gitSha: "d59d26a6761e66a0b0e3a0d1b364411d62f34c1d"
    - version: "pr-619"
      gitSha: "08e83c0262149624330b30c5e16c2d7f24ffd23a"
    - version: "pr-623"
      gitSha: "aceb201047db3f3d77c52eadaa29abc68456e72d"
    - version: "pr-625"
      gitSha: "ff92ac63a569ef041fb9c2637eec19dc3e8c9aff"
    - version: "develop"
      gitSha: "760a4660b9b61fa276d32e13208c6973324b8648"
    - version: "pr-626"
      gitSha: "1de105d357096ed5910440824869cd5d996ee0f9"
    - version: "pr-627"
      gitSha: "20889606bf491285144a9b7fce188bb973facf7b"
