app:
  image:
    repository: aeternitybot/dex-backend-testnet
    tag: "latest"
    pullPolicy: "Always"
  encValues:
    POSTGRES_PASSWORD: "AgBmbudfAbeFqZFKJlxSHNpxv/5lN4LzywLFT9oB47uIDueuBK14isyavGI2UndpmwMDULd3eEnEFSDkZpAQcewL6blz64cOCdEyQBJg5yPQVA42du7IoZXEa88lfJt63o0r4oOWOruRcmkHDSQ7HdmWyclTj/Sp2gOqsS4OU6miybahMHN+ZMob43xItJXYg8JNV5GweJyqzPG8VBB9iUHxSBo3IQX3aZDhzeArvG6Uvg90zKOmVVuGSCY+CZ7ApvDARj510vcCZlGljc/xBD1Yfx1Qp0w7ZdI3ELxJmZJTCwYJ+CFkQ03ATLFjoVGE2zZPOKsIo3J248zoII8XhtKnTd9JResCeYjm+FnCtFcp2IoAuYbTe9fXt7bZQKKnYMD2A1pYowrpzLUzuyEJOG4gsPIGcSCd3hOYqk5rQc6o72DXyh5SuiI2Th9Wa4pHAgxOo6rEPtEbFV6kfwWTsOmkHY2a/EhLJhKVRLOe5LAf7Qk8k+k5/zPErAJnIAU/dWtA3zMwgxMw6UcvjX9pddSCnJ471/EZ1OTq7bkwaqYT9M8/FrMiZqW0wJnAxDI1lGqnbW96gETnSOhYdXrMfEv68/bogRP433n/ANBoyt6tXNCkoT/JqTFZzqJ3TW9NAttYsEbGFc9ucxk8iWMfLR8/M6A3tI3oTVNuDZNFpB3ouA05qLkGotC1HmEO5MYtrvGyesXKmz/Ou9T9X4w="
    AUTH_TOKEN: "AgArBVRK8bYwJQUzDllhYIgmBnuoZLTQDIGVP5iO8G3dO3ysOYOF2uSnrv0eI2diA8R8PaxPxzs7biYto8RirAt3MMjDMbgxQXazxdRcMK/8TJoeioa4uC2U78ndJHkix8k8RkOUoxmVrN8+gAVBiQtJ+cdqHrQ921Zj5RGTfKJfhQJlu90syZzEi2K53/wkd8D5/FmYblADj8H0/TObDa0eMbfXKy9G60aSONSis8Lj88uJ94fwlqs1aPQmKZt/zgfm9/YweIosYjTi4qa9V2mADddsvLkPjiXlFFHczdtfFsA8TGg4DG0t+ybMesAo2MRvnSsLziwwtZsRYaefEzw9Sy3CvuczEKQYtBudox8fz9iVok1SrBnJUjoOLrPM+BoEOVNUlRG/DAdnen0J+3UzsUPry5fveiZaNEmL2SPvPxuKaOWeBiKtAIjSVc4Do6ykEv8/4BU4RU1AQonnQineopM7oIxuBlGMDkUkLjWVTlxYxRBMY+u1Xu99B+aneUIY5fOrTsZWEeFedXj4oerryFYQAxbFrWd4Zhs7JZPzj+rw8UoIGeaF4WTAsoJ+Oo6VLPLMsvjNONl0hWj6ws8k3bDUq3ARtWb0vhbwlV2W0KdQlsqgTOzUH6azCeJdrsZ93vmO+qcjSrMyoGCrlOYXzinLCOvvp6jZwsz5tjxxoplONfJCles4RCxyzMWqIUomtyK8YrY6qv50fO9N9Y+qbYHVvYctp077o/iDYUyrPA=="
  service:
    port: 3000
  ingress:
    enabled: "true"
    hosts:
      - host: "dex-backend-testnet.dev.aepps.com"
        paths:
          - path: "/"
  init: 
    enabled: "true"
    command: ["/bin/sh"]
    args:
      - -c
      - >-
        rm -rf .env &&
        export DATABASE_URL=postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE?schema=$POSTGRES_SCHEMA &&
        npx prisma db push --accept-data-loss
  env:
    "POSTGRES_DB": "dex-backend-app"
    "POSTGRES_SCHEMA": "dex-backend-testnet-app"
    "POSTGRES_PORT": "5432"
    "POSTGRES_HOST": "pg-dex-backend.dev.superk8s.de"
    "POSTGRES_USERNAME": "dex-backend-app"
    "NETWORK_NAME": "testnet"
    "ROUTER_ADDRESS": "ct_MLXQEP12MBn99HL6WDaiTqDbG4bJQ3Q9Bzr57oLfvEkghvpFb"
    "FACTORY_ADDRESS": "ct_NhbxN8wg8NLkGuzwRNDQhMDKSKBwDAQgxQawK7tkigi2aC7i9"
    "DOC_PAIR": "ct_2JZNDfAQHZMfoBuh32Aijd9TR8A5SHUVBzxC6x5d4sS7o8xeqN"
    "DOC_TOKEN1": "ct_b7FZHQzBcAW4r43ECWpV3qQJMQJp5BxkZUGNKrqqLyjVRN3SC"
    "DOC_TOKEN2": "ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF"
