app:
  image:
    repository: aeternitybot/dex-backend-testnet
    tag: "latest"
    pullPolicy: "Always"
  encValues:
    POSTGRES_PASSWORD: "AgApjuYculF3a3uhVMYcl/l9jIgxoe4dPlpFqHDsWVk+auRXnoJRxqOp2SwzjKOqCN59JC6Olb6UqwfCvxmzhxWBRIR7YniejtEF+cA3t/wEvIEga7caoNmjU6UtGqC7gFo3eVmOFJm7UO2JtsdIKe13xFP2Gi9lIwJWCTyLx2CJ1hUF9Mb6OFDcNehKSG94qOZTFLUvFrMgDeQ6XEwHGW7iXYneGiyg3Zl1WvW4czO+wzXvK7T1udeL6Gcf5oZ16hgj2HExIoL/vzXXCvL6bkyfTkhi+QUsK+CG7CiqNIgkNmXp0r/D+x7OBEZlkNHFKU2YGDv7G6yn1nnZkcjKgZTzkQw59jfBAHc1Dnotj5xf7yOBco0+oQR+NcU3ih84/Lcp+OHee+YZqEvJIqzLvr2YUYtHmxBxtAwUqt3sMBd0Er68uhodXCi//SPvAkW9iLYYb+ybHBiCaGp6FGB88IpCjBH3aRMHHH/3ubOZuzN8VGh1YwTXD8ekhoxqZkiD4sQEdbEApAzOiJsl7U4f7MWnyjJgq8ZJzMX9c59WPtWbTsJmPx5gsPuGDwHvcCrxQJYgNmTlubtxSOeWZttyxIRWSBUTCrWnCIzxHewiE3O0GSRXZHl4ItP8O70i8N9ze2CFul9ahllFZs9qfwNDekd29/rBug4UjvjuKi9nwr2dztuGGv3KnBCz8QGbm6Y7pdBjSNJQc6sg5qI7J14="
    AUTH_TOKEN: "AgBIOv69pfdpekRHmF3pF+nV9Yc8lTn8z6fwas7Bs6iI7eLYZzGbXi1Sefyqu+FzKBBDOb/aqL3+CvMBQlGWpO8soJT2ieWw+16OyXlDo/mKABqpS4HCEWQ8UvAAzgVHIIrH+xjGpQclasBtPCIUi8+vmC8y13Oehhwr7cR8F9z332sa09bdLetFBrAmzOlHkpROcSI6EL9RjOoY5cVMSsoBSKiS59yWCfX5LocpO++JBIqE1IlhF4HlaawqU+zukcPAPkaY9TKoy1idgSXYD3p9tc+0f1qminxWEGYqtBjAh7k9UFo0cscSSlwGyAF/kTHl2LVCyN15kKFNR7SwRyxZ87FVfqXzzv58Wl5S6N6XSezBKJD1R2+2Fxq/DHOxOXQSTI2R+GGUXGvvlKqhOPvms6GWMg4rfAMXv1fadMlQ4QgWopJ4vdKgOf3P822L1MGhsZ4uuYTG8Jf4jIFNhT66kCerYxeJhKpPY0g+uXF94GgCXvNGhQCHf2iIQXm4Jxnn8Ynvbd3R6Lc5bvJjLRnloRuwtjPMcACQb74ImGXKMV336m7XllkX9tdW8/ycdsG1ve+HP57llHG9UmNrMSsmmJ+MTt39EejsBFwQlopqTB0qx3XkLTzj2G0BiFixgg9adhbWG5UbkzrUYVwQ/1LeVoNBqIUApe54Xyrbgy03wjnV78KDhZuH8Z+LeCyfBo5QkKVPBEbPg2wUdn4MymgD8rUf5OxhuxfnKC2+MgPY9Q=="
  service:
    port: 3000
  ingress:
    enabled: "true"
    hosts:
      - host: "dex-backend-testnet.prd.aepps.com"
        paths:
          - path: "/"
  init: 
    enabled: "true"
    command: ["/bin/sh"]
    args:
      - -c
      - >-
        rm -rf .env &&
        export DATABASE_URL=postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE?schema=$POSTGRES_SCHEMA &&
        npx prisma db push --accept-data-loss
  env:
    "POSTGRES_DB": "dex-backend-app"
    "POSTGRES_SCHEMA": "dex-backend-testnet-app"
    "POSTGRES_PORT": "5432"
    "POSTGRES_HOST": "pg-dex-backend.prd.superk8s.de"
    "POSTGRES_USERNAME": "dex-backend-app"
    "NETWORK_NAME": "testnet"
    "ROUTER_ADDRESS": "ct_MLXQEP12MBn99HL6WDaiTqDbG4bJQ3Q9Bzr57oLfvEkghvpFb"
    "FACTORY_ADDRESS": "ct_NhbxN8wg8NLkGuzwRNDQhMDKSKBwDAQgxQawK7tkigi2aC7i9"
    "DOC_PAIR": "ct_2JZNDfAQHZMfoBuh32Aijd9TR8A5SHUVBzxC6x5d4sS7o8xeqN"
    "DOC_TOKEN1": "ct_b7FZHQzBcAW4r43ECWpV3qQJMQJp5BxkZUGNKrqqLyjVRN3SC"
    "DOC_TOKEN2": "ct_JDp175ruWd7mQggeHewSLS1PFXt9AzThCDaFedxon8mF8xTRF"
