app:
  image:
    repository: aeternitybot/graffiti-server
    tag: "latest"
    pullPolicy: "Always"
  encValues:
    S3_KEY: ""
    S3_SECRET: ""
  service:
    port: 3000
  probes:
    liveness:
      enabled: false
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
    readiness:
      enabled: false
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    storageClass: gp2
    size: 50Gi
    mountPath: /app/data/backup
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "graffiti-server-testnet.prd.aepps.com"
        paths:
          - path: "/"
  env:
    "NODE_URL": "https://testnet.aeternity.io"
    "IPFS_URL": "http://ipfs.prd.service.aepps.com:5001"
    "S3_BUCKET": "aeternity-superhero-graffiti-prd"
    "SYNC_STORAGE": "true"
    "S3_REGION": "eu-central-1"
    "CONTRACT_ADDRESS": "ct_uJ5NKmuX7eX79QPerixR7Z8zEdxKCKJw1yzHjX1tsmRP17tuP"
