
app:
  encValues:
    PG_PASSWORD: "AgA3LvJuMhwmH0+bVQ6T9KfCz0aSb4BZMlNaD0lMhSxHVT491uc79mDqIe+xNiRpLBKSe0ftbviqnlPTD8lr6cGz/jhFTW9wbJVIIGWUUqXzILJBATnnKh1hGGRRgbhpzXVnhRQ7b6Wv3JTOmPRYEz6Q6z/nez/C9FdqzzkDLOaKDdvhcv/6VwFnF/eywkQkrmGS9MWYoB5FuangEvgVq+tmWJDOidDXpcgaGZjPlv2TJ2WHqOe7q1NqpMW7P17ejlTnVLBswWOiJgf+AhPZSSE227W1v6T2+V6SrmLrEJcu1llse/imtevGIaFglO78fLy64E7rsL6c95llK2OwQdTfcU5oKzYmVjoes3h3H1WN9XgKumGrBZ/wutn8TEtVXszVkaqtwdDYPj3hjGgzyCDAf4AZdThQcI2DHq7CT80+qXlNNl29TlUJl8ZWhmm03OTstKGzBtdTbkWTp4pIZuY9ADz7hUPD4+3KYEMwsNmBDjoXVBiuHpL2JiERghQKmrFC4Iugb2f63kTcNY63rGGeIVAXXnsdUQcsdL/vfUcToz9v6M2g419gPlao68ZpiQmaZJIQE+KDBRnv2L0zntHV+6kNY4FmkedRNrPtiCL5A6FXucai5IoPY7LQuYT06SsDFSuoLo2hYLT2EqEoP/4dKgKuNAaIjEE0VOYwNM1lTkGcnKgRSIsB5vG71ktsqB1R14f7vup0N7Nq"
  image:
    repository: aeternitybot/ga-multisig-backend
    tag: v1.1.0
    pullPolicy: "Always"
  resources:
    limits:
      memory: 150Mi
    requests:
      cpu: 300m
      memory: 150Mi
  service:
    port: 3000
  serviceMonitor:
    enabled: false
  probes:
    liveness:
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
    readiness:
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
  ingress:
    enabled: true
    hosts:
      - host: "ga-multisig-backend-testnet.prd.service.aepps.com"
        paths:
          - path: "/"
  env:
    "PG_DB": "ga-multisig-backend-testnet"
    "PG_PORT": "5432"
    "PG_USER": "ga-multisig-backend"
    "PG_HOST": "pg-superhero-backend.prd.service.aepps.com"
    "MIDDLEWARE_URL": https://testnet.aeternity.io/mdw
    "NODE_URL": https://testnet.aeternity.io
