app:
  image:
    repository: aeternitybot/dex-backend-mainnet
    tag: "v1.0.0"
    pullPolicy: "Always"
  encValues:
    POSTGRES_PASSWORD: "AgAoekXoCRLsYEre4t7kdW43aixQ1pjlLKoWxMU8EktrhKNT65RTpusDRurrMmK48Dgez9OVGZNv8gBpMMOtcnbAhSGei/2s3YDVsUiX0jRTpDyo5VsK7dNlKMJU6bULO+eurMD85XZoi0Q88z75MlJ/3fDaOQT3E1/1b2Z9EnCpkqhE9vJHaIpE12iIMHWiYjUlIXO5lIjBhJFtzoO19CpbSo71YzxLSpAX3wjNTcFQDoepC6lgCrTzUDx/7QxegA1BIdJOoVSoG8HULFpofsva3Oo+hj1z2PSdRLAdqCHamikJ7J9UroXsBmLtpD6wMwPtGBfPvGiC4H7RhdL5PcHLhcPHA4QJf6nrWWh8uiFLTmbqTvl7phOxOhYHZGa5ZMmsSrIkHlsk2i14keBYrZGmJkRQ1WSc9sojug09Cv6LBYI1s88c4q034LZpPR8PT4EC+NACcujXlnA81O06iDaVFNlPYukL6PJETbYGIXza4PkZxIvCXwgKlPZORL5Xg7sT9xZT26nJ5k12n2IXpijS77VuJB+SO4qtD6rvldYtBZhgG8Rd19LEykIkX92gIKg84h0GEKKCF+66PtOCc2xriT2OJSPzy3jYWjJIdcPeQSP9FACDOGV+bgAnCbemGhE9ARtWl/z/uJZVt1FpXWkFY/pQtIaob6msUiv8IJ1rdbf8QResja2BgSSutZZFN5N7yYOvg1jxBEVNNQI="
  service:
    port: 3000
  ingress:
    enabled: "true"
    hosts:
      - host: "dex-backend-mainnet.dev.superk8s.de"
        paths:
          - path: "/"
  init: 
    enabled: "true"
    command: ["/bin/sh"]
    args:
      - -c
      - >-
        rm -rf .env &&
        export DATABASE_URL=postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE?schema=$POSTGRES_SCHEMA &&
        npx prisma db push --accept-data-loss
  env:
    "POSTGRES_DB": "dex-backend-app"
    "POSTGRES_SCHEMA": "dex-backend-mainnet-app"
    "POSTGRES_PORT": "5432"
    "POSTGRES_HOST": "pg-dex-backend.superk8s.de"
    "POSTGRES_USERNAME": "dex-backend-app"
    "NETWORK_NAME": "mainnet"
    "ROUTER_ADDRESS": "ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3"
    "FACTORY_ADDRESS": "ct_2mfj3FoZxnhkSw5RZMcP8BfPoB1QR4QiYGNCdkAvLZ1zfF6paW"
    "DOC_PAIR": "ct_NNmdSt3Ws4r87pESGKrhGb7VJmC8zpZymXNJKHY8bTLaFttsi"
    "DOC_TOKEN1": "ct_2dE7Xd7XCg3cwpKWP18VPDwfhz5Miji9FoKMTZN7TYvGt64Kc"
    "DOC_TOKEN2": "ct_7ur9ypT3a4tjxxv5iG6zEQDQhysNtCKr6tyc7PkqhtRmEw6yY"
