app:
  image:
    repository: aeternitybot/dex-backend-mainnet
    tag: "v1.0.0"
    pullPolicy: "Always"
  encValues:
    POSTGRES_PASSWORD: "AgBdkqBgDpi7lVwaki1ye5m0HK0U3Qg2T9b6OSLCt4TJ0Z+a3XN39VfShhJtGcTlAYCLkKOlUb1yCgryuIVUDxM637dx4UYC8K44smHsGBdVOUrWqdZliyek4R+wv0wCzyWb7t/ZMpf4ffKvD+IKwaRN0Fm5xF3XhjbeFijkQlsfX/YmXbaQ/LVF2h3L/IM0TuJZ04AxuMXoz62mVMbZeykWjMP0lZ7gaIto5vjKKU4s/yh0G82TBpD6MizdCplmVAGy3mo/vXAny2qCh3QO/nz28CWltXpUtdacrQBP44xcXpeP0ARkFR4mOKgZzH0u9AYQGOqGV7i+C1zh9WX/c+I1hVH3JqayX4LlfsJyC/Xfs0qBXQbdPWk/WOGLuBvE48NEzcVuK6/+XReviQRH/GSv90ybN/ZUMkHHL1eOh/FSasEDabkAv+iK5nKoIqYxJ3LbjyanL9g2dGkRMZ4fd9eRJ0SUdOWa+7fR9fyJ7QNgSBdmRi5urfHVU++YBLjo7wWi73tmyzhfeXQ5UM81Nd8g7AfzMhf0Zzfg+uYcbEIun+X94jpWyf22KuOdeZ9Ocr3qzVVMyDkbjaSMBnIWy9nUE0jQ38q7UygYziAE3wWaJrDLky69N9KfpEhr8KNspppboqUGEUk/44xvV/BhjsXwbi/6JkBapoTa+0ZTRdqinTaYZk8M4wDIC0LYktX1fKDG8gRwJ36SQXx5Bjk="
  service:
    port: 3000
  ingress:
    enabled: "true"
    hosts:
      - host: "dex-backend-mainnet.stg.superk8s.de"
        paths:
          - path: "/"
  init: 
    enabled: "true"
    command: ["/bin/sh"]
    args:
      - -c
      - >-
        rm -rf .env &&
        export DATABASE_URL=postgresql://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE?schema=$POSTGRES_SCHEMA &&
        npx prisma db push --accept-data-loss
  env:
    "POSTGRES_DB": "dex-backend-app"
    "POSTGRES_SCHEMA": "dex-backend-mainnet-app"
    "POSTGRES_PORT": "5432"
    "POSTGRES_HOST": "pg-dex-backend.stg.superk8s.de"
    "POSTGRES_USERNAME": "dex-backend-app"
    "NETWORK_NAME": "mainnet"
    "ROUTER_ADDRESS": "ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3"
    "FACTORY_ADDRESS": "ct_2mfj3FoZxnhkSw5RZMcP8BfPoB1QR4QiYGNCdkAvLZ1zfF6paW"
    "DOC_PAIR": "ct_NNmdSt3Ws4r87pESGKrhGb7VJmC8zpZymXNJKHY8bTLaFttsi"
    "DOC_TOKEN1": "ct_2dE7Xd7XCg3cwpKWP18VPDwfhz5Miji9FoKMTZN7TYvGt64Kc"
    "DOC_TOKEN2": "ct_7ur9ypT3a4tjxxv5iG6zEQDQhysNtCKr6tyc7PkqhtRmEw6yY"
