app:
  image:
    tag: "master"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/frontend-entry-points: "https"
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - host: "base.dev.service.aepps.com" # has to be changed/disscused
        paths:
          - path: "/"
    tls:
      - hosts:
        - "base.dev.service.aepps.com"
        secretName: aepp-base-cert
