app:
  image:
    tag: "master"
  ingress:
    enabled: true
    hosts:
      - host: "base.dev.superk8s.de" # has to be changed/disscused
        paths:
          - path: "/"
    tls:
      - hosts:
          - "base.dev.service.aepps.com"
