app:
  encValues:
    POSTGRES_PASSWORD: "AgCgYrqn03UFNgZGBazuMCTwMIFAT/ZSbBRbndwbReAwQH/77Jp5BxUW1FgkdwGJwC1t+lFW7Yaj1OWplWPpCxDBR0EI/AdI+fLuwRPwvaKmvm2TEu05KqWKbnYTnTgWB/0QXGZ7XUv0LM7YpmqM1fkZidcqijpabCgK1JyravGbMAB0luyQotY7D1uw663IgB/8dirtFJUZllCdQ8Tu9LWa1Aw+e0gUJdQupTkih9G9XhQjwnFc+9Bbxhl9KpB7xx6Yk4Z1P44fYWnIlER5nPS2ZPuyRppjJ8oTBm7Bz4KJDOYgGdC2sZ6DbSbFOOHAo2TXbJouBA3HGy0oGn/bVwPDm6aQanvfKVQVpcbC3WrV3O/XzNRXHmJhDQSH8QHW6AxxFnYScYbToqn/v2ri8gsDPec/qFWJa8e5/tgd2tdSXM4XtHQ7kn7cYjWIE80U7pjD0SVHHOZy2Jpp67Yi6e4hwb27qCPOBuQUcsBwL06+aPtqNsrYxarvlGT92VSJZdN00PhtTFc4kI1OgNAk4lctHD9viuwyrwKy0g8LfNc9uXhePbjj7vkV7bjsKvnmMnjihnTLHNoHbjGbzlt4DbtLl3ORt0OPopWxPSjkJJv0jV7kYsDNh1KSAhN8MNNdqR0NDTpCzxNkfQ5K99hdDP+voAlxGGHW7BzQwvrbiPBkhEbN9nuCL5J8lMgpY7/EGMy15K1HKmlTwXEL5ss="
    AUTHENTICATION_PASSWORD: "AgCLcjqo7u5tpwoT9GfLf4L79Qr2s7fAbt1eqDBcYC/vBzNV5BnHWKAsKe9wIW2EMwtEK1whl3bnk+VXXUqYPkI944LVmjac8YZJdK2gk9BFneI7U3Qy2VR4N9zKiaLYEltiFcQ1T1Vg9U4uXUFaIxlnO6DklEkrkKIyM+mPKqLX41u/sEvvIfKYL4+embxH//0LyzJn1FwrS5VKDYDL9nfWGO4n1has2Ivxe2+bMDwAgBnQf0qaamKR5T7moOZ99VcOrNWgfjc4cy4L1RN07fQNRRR6pVwhsEi5IS+i0UeMGCB2Y2f8tspFZs6IxKS56+wSzWzQJlxRv878p7bNlhHVdoUN5Ao3jC/uoVXBNrKNn0E9hYJfbHnCfRlS9pqO89dBGwy6UP9AAEdpt/MQ6RxjV5uGJCbZxCQQdUFUqfZtr6Wjm+LXjPF8ZRmhRjaloj9mn4YD2pfZiH3iwcYysdK8Vhtl0cdeV2UzVueuN2+D+zj3sttbu1XCyVr77Wes1T/EjIFp/6j39neqTP/WPgfM6i90im202YiC7RsJJOmkA8aniB1hHUFfVWlZn+MBZ5/nECnj0ip3CuDD/KRk6itd82C3nKQcAam534EVSo4Wqc4J27bOKQDkpQ0j1W6wSgm4ppeTFfj7ymiWv4q97S+A6hOxP8b+2jyMCjU21C6+wBy/VhkGa14stFnjkGKDJalAbte5zm5yqwO8JxtN1knP"
    PRIVATE_KEY: ""
  env:
    "REDIS_HOST": "10.0.2.6"
    "REDIS_PORT": "6379"
    "NODE_URL": "https://mainnet.aeternity.io"
    "COMPILER_URL": "https://latest.compiler.aepps.com"
    "CONTRACT_V1_ADDRESS": "ct_2AfnEfCSZCTEkxL5Yoi4Yfq6fF7YapHRaFKDJK3THMXMBspp5z"
    "CONTRACT_V3_ADDRESS": "ct_2Hyt9ZxzXra5NAzhePkRsDPDWppoatVD7CtHnUoHVbuehwR8Nb"
    "TOKEN_REGISTRY_ADDRESS": "ct_2n76BQCN3zNEjuEvHFNZtgyWPc5zizy47wNrUT3RHP2MrPKhbq"
    "ORACLE_CONTRACT_ADDRESS": "ct_7wqP18AHzyoqymwGaqQp8G2UpzBCggYiq7CZdJiB71VUsLpR4"
    "MIDDLEWARE_URL": "https://mainnet.aeternity.io/mdw"
    "IPFS_URL": "http://ipfs.dev.superk8s.de:5001"
    "PUBLIC_KEY": "ak_yrVCHP97UWfCRGMCaojBjdSKuXD3yyC8NkzkReURd4t3jbCQW"
    "AUTHENTICATION_USER": "user"
    "NODE_ENV": "production"
    "WEBSOCKET_URL": "wss://mainnet.aeternity.io/mdw/websocket"
    "ORACLE_GETTER_ADDRESS": "ct_anbp2U5VUsF6PkrX1ER1hSqj76Krpvqy97c5JBLmubBecCWui"
    "CONTRACT_V1_GETTER_ADDRESS": "ct_NR7Bd7j5LRdzvKZmrMagMkfxzG8ZPWseKQkdwWootpq4kAJY2"
    "CONTRACT_V3_GETTER_ADDRESS": "ct_2NdZ6PX9tZHWFhgcoYjthYNFF15qxjDwFSsNXRPeajEWazxkTo"
    "POSTGRES_USER": "postgres"
    "POSTGRES_DB": "superhero"
    "POSTGRES_HOST": "pg-superhero-backend.superk8s.de"
  image:
    tag: "latest"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  service:
    port: 3000  
  ingress:
    enabled: true
    hosts:
      - host: "superhero-backend.dev.superk8s.de"
        paths:
          - path: "/"
