app:
  encValues:
    POSTGRES_PASSWORD: "AgBGU0ZHfXmR1AIfHfXcRMIxwU90WhrChYuf2YPGTQARmqElvDeH54a1iK8c8Wp+xHihGJNockab3wI02S8NhY12uIAJqIV8tGejMElvHH+MDi5VUuG4Q8C+XxQPROciDOg18ftVQQgDu78EySaEMfXmW8r9JXa90R3iKoltgX9t/wcAYiN0S3874joHdVGW34s7bpCQcF4BvVbXoJ8z8YPhax2AmdIv66EUF3dEnLfunBaKIfSglCPQumsrTGj60ouOkNMX73xfdVVzZsExszf63sjK0ljAYqfs9zbJxj9OIDXL4RV8qfZGLeqjlLjfb+AhP5aAPJCCI0B15LKjxomRozSRIk8z7VOFgYp+wQWmR7n+7nlfkt9O03QD9gRC1Qmmpbh0FEw/JD8iHr+kJ08vOahspd7gBP3hjUUjq8/p7iXYAzYKNiq9Peqzi0HmrQnVO0OztHoASqstUGXKypfDJuPKlqljHdoEdQJskqYGwMkYXk2yygtL200euSlCtWXMgd/9/J+n+3AknOjQ/rXpnAH0Qzf1s+3BtW1xiKn7c1dF+0z3XAYHIxF3j0SivAL2/rq7r91VuPXlMYJczxNV8h7GD0CCZY+X4X9jHgOkbOQ3lv3CQTcdhi0iiTgoUVXYUSp3a5ocJwA3q7sz3Cq5P6tbh3KRakN4QwpXqPAguirwqAdwJBT3QitPbAkBFh1rWS3VqVYulZPIrcM="
    AUTHENTICATION_PASSWORD: "AgAsPWppQJsV5iBdrwD8jH0erFK5G5sWP9D5Se9Nm+KESlgDzB3FoUrXT2YVG0qe63zkZwflNQg/nB15cPPbOr3JJCpKtWvZ5GjY9FJw+Ppaw2Uy6qe3SjgWaHsDJGtHpCDFkAMUvG386y2a6A48toqpod9q3z31EgMo8fHyoHENexETgPP2jzO0tMGxGLrc1ogpKnmrdXMcIh7FycPQZ57LxhefgRKLQCly1g074PLql89OcT2hr6M9jUKrG4/Pgs3eqqWyto3wtiOsJRNa4HSb41uw6sCDExDfhpy6J14p/oesvdy5wfrIisJNdQqcof8lJLAVJRXdNQyu2k2QWeGribonq5T80JA2p1y6vKi0go+i0eUOdJWb//bZvOaBJjZ1hniQ+nUKKFtrBiieXCAz2todXXI8NHAj/Ns2eY6wFuKt5XLPoQHgHVh9UhHmW6NPHEigxmGlGbN2x+VtiCczpdGM5hTucu7I9Nl+WulXbfC1B1x09EGzetvyb9xsSevsDuV25/CSh9ApUYE3vtJVrJtmwrZsOMR/hkCVkI43eHTHuedNJtcddoWMkXnmWDilE/n77qasi8BeGuE1G1zdPC7CEa+dL2Rj7Xjv4ksvpcADqPyJaxQWfDu/Tzq+RtgOXpudtHknTlA9XElk5ptQ7RbHJ1yf4JhgEw+wXFNvEwKR/nkOafYvluRdKD802R6XRGTQFHOwXBZRPt0esiOitME="
    PRIVATE_KEY: "AgA2xemj9KIDIlFaySMwJWaIVWvT+2VQ0kSJRUv2XfurPK8hZU/IMvI5ewULUZe48K/VhHDZVc7j20tb68EPOxjh2XaVoKZ63Tk/C+lNpUfiqVgOJcFYWCKs2leFDjTi73Jp9HZZqi0fOzCaL5sMVMU2SC4w12xXYi+PwXVZOJl4MQoNFBA+GfU2drBznJ54vxZoCrnKBpsKM8vdxi0mkwN1YVwKnck10vn3s4iC0k506/RRMkp+50PTV6sSjUi+DNXAWvXYH6CAAYXxZgNlitr9EWfAlZXlwm8vWmIOH0dOsMNfy1BvB0H3mCilhe9X5XVmrzqb8lOASzgqSyBAPuXy9ahseW3Quk5FIt1CPgQ7vusA6P2ft1mpmyJ/bFm5xkhh8YGKzMToV6Flfv9/CDoNPV9Yq6pmmI+IRTxF4zJf3zor9d19j2H1EBxpP5hH2XkiKpmjgRqnO3KQH1yeaGbHsKn+nwoNhoPB3QgoPOs2AkrYm2H4R7KeU55iNhxEwIJq5GdJK8eV+Jkc0gwlkx6vBJ5oiIaBJh4T72s1q4PuT2RqEcdwWrtjFggaYbVm09uOQ0vNl4+QIU11Kbcq1v2G6SUABDDsEeBTWMimEG33t55uy+JJ6d+C7C7KlHD7cdfJejVaZOZIM47cRNIncMGAPkMes778bfrW3T4OwLAtuiGDS9wcRSGM92g/sHDrLM2iUldAHZwlEt3pePIota9WNzSdFUrIiX7/LuBG/ZQg3HuugLFamBiHk8/nTlDSp1cSUese/Gjx2rjZlW1LATgfk0FpjTYjome8uI2WBR08coIp8FWcDajj+IvSArqJQ4/znsWzYNicor3VGDXU4nFZ41Bffua8H/yMQw7o/alTjQ=="
  env:
    "REDIS_HOST": "172.16.1.6"
    "REDIS_PORT": "6379"
    "NODE_URL": "https://mainnet.aeternity.io"
    "COMPILER_URL": "https://latest.compiler.aepps.com"
    "CONTRACT_V1_ADDRESS": "ct_2AfnEfCSZCTEkxL5Yoi4Yfq6fF7YapHRaFKDJK3THMXMBspp5z"
    "CONTRACT_V3_ADDRESS": "ct_2Hyt9ZxzXra5NAzhePkRsDPDWppoatVD7CtHnUoHVbuehwR8Nb"
    "TOKEN_REGISTRY_ADDRESS": "ct_2n76BQCN3zNEjuEvHFNZtgyWPc5zizy47wNrUT3RHP2MrPKhbq"
    "ORACLE_CONTRACT_ADDRESS": "ct_7wqP18AHzyoqymwGaqQp8G2UpzBCggYiq7CZdJiB71VUsLpR4"
    "MIDDLEWARE_URL": "https://mainnet.aeternity.io/mdw"
    "IPFS_URL": "http://ipfs.prd.superk8s.de:5001"
    "PUBLIC_KEY": "ak_HryHrgaVUSxezLQBfNENhptKeXk6tpg4kjWBk88nsU5RJvhNk"
    "AUTHENTICATION_USER": "admin"
    "NODE_ENV": "production"
    "WEBSOCKET_URL": "wss://mainnet.aeternity.io/mdw/websocket"
    "ORACLE_GETTER_ADDRESS": "ct_anbp2U5VUsF6PkrX1ER1hSqj76Krpvqy97c5JBLmubBecCWui"
    "CONTRACT_V1_GETTER_ADDRESS": "ct_NR7Bd7j5LRdzvKZmrMagMkfxzG8ZPWseKQkdwWootpq4kAJY2"
    "CONTRACT_V3_GETTER_ADDRESS": "ct_2NdZ6PX9tZHWFhgcoYjthYNFF15qxjDwFSsNXRPeajEWazxkTo"
    "POSTGRES_USER": "superhero"
    "POSTGRES_DB": "superhero-backend"
    "POSTGRES_HOST": "pg-superhero-backend.prd.superk8s.de"
    "POSTGRES_SSL": "false"
  image:
    tag: "psql"
    pullPolicy: "Always"
  probes:
    liveness:
      enabled: false
    readiness:
      enabled: false
  service:
    port: 3000  
  ingress:
    enabled: true
    hosts:
      - host: "superhero-backend.prd.superk8s.de"
        paths:
          - path: "/"
