
app:
  encValues:
    PG_PASSWORD: "AgAbMK1Uan35WLU6XMM1GtlpIMwYQbIaLSirtVumrDYvBMIxMaMV06yuCp5yGWxJ5MpQ+iVoVwZcUwF+66NH+zVPx0kcheduL+BtddaY4oFGEuvurNIOt1JWEgftVyBd/G0YyNto3aqHHGUTtUqmb7KoQdSmxii0F2vKhtvcsnCMyd6YMjpRGPX1X9m66M2BVjjJXNxl5kzWkdFG5H0ooDQBEaUY1DkMZYyNePy6nr95aVP+o6Zm6ssSDRMOjdAPEF1+BuXzXj8dtYHVHH+Xa7Oxf0DLImKa7M8UZaVGapGUchkBC+HX2t9Sz97igIpN4kw7OExoMsNuzaeWHh5tlqkbg0LnvqqUayw4HefhMTJc/LZJo9DBduCrT4VQwtiG56CQ4Rm+rn5hZRmfphBF7A3oikt4AnW00ZTwv618LadzJ28o8YcpfHfbSRPAjxA9T933MuhRhNiTUeIYlwbmCU8bTvzrnfyI+CBvt2ZBOMB/Sz2Xb9jyv/RYajjC9juXnXDLhTWahbKw6LOOGTGc9CRP4RZI748eFlW937g9yWFtHPolRD5u3r8JhHjL9cED6/YsRBM8c9PSw2iz3smOsUFDqzgJrqkeJ6CJpxUEOjaoA0mSxUX7x+cCl2GftZcfvlzUoRh5C0m+Uh8xxf/E21j5El53zlgXMVIK8TxKfHAThQ/brblc7/JkVKD+OMERfcFlpr11rJXUHlk"
  image:
    repository: aeternitybot/ga-multisig-backend
    tag: v1.1.0
    pullPolicy: "Always"
  resources:
    limits:
      memory: 150Mi
    requests:
      cpu: 300m
      memory: 150Mi
  service:
    port: 3000
  serviceMonitor:
    enabled: false
  probes:
    liveness:
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
    readiness:
      config:
        httpGet:
          path: /health
        initialDelaySeconds: 120
        periodSeconds: 120
        successThreshold: 1
        timeoutSeconds: 60
  secrets:
    external:
      remotePrefix: /k8s/prd-0e9c
  ingress:
    hosts:
      - host: "ga-multisig-backend-mainnet.prd.aepps.com"
        paths:
          - path: "/"
  env:
    "PG_DB": "ga-multisig-backend-mainnet"
    "PG_PORT": "5432"
    "PG_USER": "ga-multisig-backend"
    "PG_HOST": "pg-dex-backend.prd.service.aepps.com"
    "MIDDLEWARE_URL": https://mainnet.aeternity.io/mdw
    "NODE_URL": https://mainnet.aeternity.io
