app:
  nameOverride: superhero-wallet
  image:
    repository: aeternity/superhero-wallet
    tag: "latest"
  ingress:
    enabled: true
    hosts:
      - host: "superhero-wallet.prd.service.aepps.com"
        paths:
          - path: "/"
