app:
  image:
    tag: "latest"
    repository: "aeternitybot/aescan-frontend-mvp"
    pullPolicy: "Always"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: "aescan-frontend-mvp.prd.service.aepps.com"
        paths:
          - path: "/"
