{{ $versions := .Values.versions }}
{{- $dedup := dict "seen" (list) "result" (list) -}}
{{- range (append $versions (merge (dict "version" (default .Values.image.tag .Chart.AppVersion)) $)) -}}
  {{- if and .version (not (has .version (get $dedup "seen"))) -}}
    {{- $_ := set $dedup "result" (append (get $dedup "result") .) -}}
    {{- $_ := set $dedup "seen" (append (get $dedup "seen") .version) -}}
  {{- end -}}
{{- end -}}
{{- $allVersions := get $dedup "result" -}}
{{- range $key, $val := $allVersions}}
{{- if $val.version }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.versionedFullname" (merge (dict "version" $val.version) $) }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
    app.kubernetes.io/version: {{ $val.version }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/version: {{ $val.version }}
{{- end }}
{{- end }}
